# Generated by Django 3.2.19 on 2023-07-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_alter_category_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('expreyance', models.CharField(choices=[('Good', 'Good'), ('Average', 'Average'), ('Best', 'Best'), ('Bad', 'Bad'), ('Worst', 'Worst')], default=1, max_length=100)),
                ('file', models.FileField(upload_to='')),
                ('description', models.TextField(max_length=500)),
                ('product_name', models.CharField(max_length=100)),
            ],
        ),
    ]
