# Generated by Django 3.2.19 on 2023-07-19 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0004_alter_category_category_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('short_description', models.CharField(max_length=300)),
                ('long_description', models.TextField(max_length=1000)),
                ('product_price', models.IntegerField()),
                ('product_discount', models.IntegerField()),
                ('product_thumbnail', models.ImageField(upload_to='product_thumbnail')),
                ('product_category', models.ManyToManyField(blank=True, null=True, to='backendapp.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_gallery')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='backendapp.product')),
            ],
        ),
    ]
