# Generated by Django 3.2.19 on 2023-07-19 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0005_product_product_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='product_thumbnail'),
        ),
    ]
