# Generated by Django 3.2.19 on 2023-07-19 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0006_alter_product_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_gallery',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='backendapp.product'),
        ),
    ]
