# Generated by Django 3.2.19 on 2023-07-22 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0005_review'),
        ('backendapp', '0007_alter_product_gallery_product'),
    ]

    operations = [
    ]
