# Generated by Django 3.2.19 on 2023-07-22 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0008_merge_0005_review_0007_alter_product_gallery_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ManyToManyField(blank=True, to='backendapp.Category'),
        ),
    ]
