# Generated by Django 3.2.19 on 2023-07-25 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0010_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
