# Generated by Django 3.2.19 on 2023-07-25 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0012_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
